name: 'workflow_run status'
description: 'Associate workflow_run status with the base commit of workflow_run event'
author: 'haya14busa'
runs:
  using: 'node12'
  main: 'dist/index.js'
  post: 'dist/index.js'
